//! Indirect draw buffer management for virtual geometry.
//!
//! The [`IndirectDrawBuffer`] wraps a `wgpu::Buffer` with `INDIRECT` usage
//! and provides helpers for uploading CPU-generated draw commands and issuing
//! them via `draw_indexed_indirect`.

use bytemuck;
use super::meshlet::DrawIndexedIndirectCmd;

/// GPU buffer holding an array of [`DrawIndexedIndirectCmd`] entries.
///
/// Each entry corresponds to one visible meshlet and is generated by the
/// CPU culling pass (or a future GPU compute pass).
pub struct IndirectDrawBuffer {
    pub buffer: wgpu::Buffer,
    pub capacity: usize,
    /// Number of valid commands uploaded this frame.
    pub count: u32,
}

impl IndirectDrawBuffer {
    /// Allocate a new buffer with space for `capacity` draw commands.
    pub fn new(device: &wgpu::Device, capacity: usize, label: &str) -> Self {
        let byte_size = (capacity * std::mem::size_of::<DrawIndexedIndirectCmd>()) as u64;
        let buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some(label),
            size: byte_size.max(64), // wgpu min buffer size
            usage: wgpu::BufferUsages::INDIRECT | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        Self { buffer, capacity, count: 0 }
    }

    /// Upload `commands` to the GPU buffer (truncated to capacity).
    pub fn upload(&mut self, queue: &wgpu::Queue, commands: &[DrawIndexedIndirectCmd]) {
        let count = commands.len().min(self.capacity);
        self.count = count as u32;
        if count == 0 {
            return;
        }
        queue.write_buffer(
            &self.buffer,
            0,
            bytemuck::cast_slice(&commands[..count]),
        );
    }

    /// Issue one `draw_indexed_indirect` call per uploaded command.
    ///
    /// This loop is correct for any number of commands but becomes a
    /// bottleneck for very large draw counts.  For high-performance scenarios,
    /// replace with `multi_draw_indexed_indirect` (requires the
    /// `MULTI_DRAW_INDIRECT` feature).
    pub fn issue_draws<'a>(&'a self, pass: &mut wgpu::RenderPass<'a>) {
        let stride = std::mem::size_of::<DrawIndexedIndirectCmd>() as u64;
        for i in 0..self.count as u64 {
            pass.draw_indexed_indirect(&self.buffer, i * stride);
        }
    }
}
